CREATE TABLE IF NOT EXISTS `post` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(50) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `like_count` int(20) DEFAULT 0,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `comment` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `post_id` INT(20) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
